input:
  file:
    paths: [ ${LOG_FILE} ] 
    scanner:
      lines: {}
  processors:
    - rate_limit:
        resource: slower
pipeline:
  processors: 
    - log:
        level: INFO
        message: Logging message from file -> ${! message }
    - mapping: | 
        root = this
        root.machine_code = deleted()
        root.reference = deleted()
        root.request_id = deleted()
output:
  switch:
    cases:
      - check: this.log_level == "ERROR"
        output:
          kafka_franz:
            seed_brokers: [ ${RP_ADDRESS} ] 
            topic: "raw_error" 
      - check: this.log_level == "WARNING"
        output:
          kafka_franz:
            seed_brokers: [ ${RP_ADDRESS} ] 
            topic: "raw_warning" 
      - output:
          kafka_franz:
            seed_brokers: [ ${RP_ADDRESS} ]
            topic: "raw_info" 