input:
  kafka_franz:
    seed_brokers: [ ${RP_ADDRESS} ] 
    topics: ["backend_error"]
    consumer_group: "rpcn-lab3"
pipeline:
  processors:
    - workflow:
        meta_path: meta.workflow
        branches:
          geo_location:
            request_map: |
              root.ip = this.client_ip
            processors:
              - cached:
                  key: '${! ip }'
                  cache: ip_cache
                  processors:
                    - http:
                        url: http://localhost:8081/geo/lookup
                        verb: POST
            result_map: |
              root.ip = deleted()
              root.ip_continent = deleted()
              root.geo_info = this.geo_info
          error_count:
            request_map: |
              root.ip = this.client_ip
              root.source_system = this.source_system
              root.message = this.message
              root.priority = this.priority
            processors:
              - http:
                  url: http://localhost:8082/error/count
                  verb: POST
output:
  kafka_franz:
    seed_brokers: [ ${RP_ADDRESS} ] 
    topic: "backend_error_geo" 
cache_resources:
  - label: ip_cache
    memory:
      default_ttl: 360s
